#!/usr/bin/bash

TESTMAKER_MYSQL_USER=testmaker_dev TESTMAKER_MYSQL_PWD='testmaker_dev_pwd' TESTMAKER_MYSQL_HOST=localhost TESTMAKER_MYSQL_DB=testmaker_dev_db TESTMAKER_TYPE_STORAGE=db TESTMAKER_HOST='0.0.0.0' TESTMAKER_PORT=5000 python3 -m website.v1.app

